version: '3.8'

services:
  credit-simulator:
    build: .
    container_name: credit-simulator-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    stdin_open: true
    tty: true